# Generated by Django 4.1.10 on 2024-11-30 16:10

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('location', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('units', models.CharField(default='pcs', max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('departments', models.ManyToManyField(blank=True, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_department', to='home.department')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.profile')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_department', to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('is_protected', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(10, 'view'), (11, 'add'), (12, 'edit'), (13, 'delete')])),
                ('subject', models.IntegerField(blank=True, choices=[(20, 'Profiles'), (21, 'Roles'), (22, 'Inventory'), (23, 'Receipts'), (24, 'Products'), (25, 'Categories'), (26, 'Departments')], null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.role')),
            ],
            options={
                'unique_together': {('role', 'action', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ReceiptProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.receipt')),
            ],
            options={
                'unique_together': {('receipt', 'product', 'price')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('goods_received', models.IntegerField(default=0)),
                ('goods_issued', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.product')),
            ],
            options={
                'unique_together': {('department', 'year', 'month', 'product')},
            },
        ),
    ]
